# Generated by Django 4.1.7 on 2023-03-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
