# Generated by Django 4.1.7 on 2023-03-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images2',
            field=models.ImageField(blank=True, default='933_ps.jpg', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='images3',
            field=models.ImageField(blank=True, default='933_ps.jpg', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, default='933_ps.jpg', null=True, upload_to='products/'),
        ),
    ]
